// app/api/mint/route.ts

import { NextResponse } from "next/server";

export async function POST(request: Request) {
  const { recipientAddress } = await request.json();

  const crossmintURL = `https://staging.crossmint.com/api/2022-06-09/collections/${process.env.NEXT_PUBLIC_CROSSMINT_COLLECTION_ID}/nfts`;

  try {
    const response = await fetch(crossmintURL, {
      method: "POST",
      headers: {
        accept: "application/json",
        "content-type": "application/json",
        "x-client-secret": process.env.CROSSMINT_API_KEY!,
      },
      body: JSON.stringify({
        recipient: recipientAddress,
        metadata: {
          name: "First event",
          image: `https://base-frame-xi.vercel.app/9.png`,
          description: "This is a random event generated by Proof of Friends.",
        },
      }),
    });

    if (response.ok) {
      const data = await response.json();
      return NextResponse.json(data, { status: 200 });
    } else {
      const errorData = await response.json();
      return NextResponse.json(errorData, { status: response.status });
    }
  } catch (error) {
    return NextResponse.json({ error: "Failed to mint NFT." }, { status: 500 });
  }
}
